# top level stuff you probably don't need to touch
highlighter: rouge
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# Achieve your personal greatness
url: http://toldy.github.io/
baseurl: ""
title: Julien Colin
author: Julien Colin
description: Personal blog and resume
avatar: profile.png
email: juliencolin54@gmail.com
github: Toldy
twitter: Toldy_
linkedin: colinjulien
stackoverflow: users/2618071/toldy
#Comment out if you don't want disqus
# disqus: username


# needed for travis-ci build
exclude: [vendor]
